### PR TITLE
Test of color

### PR DESCRIPTION
**Pull request by mlep**

### CODE REVIEW

**Comment by koppor** [comment]
Should I really merge this? I wonder why the commit is labeled "test". You also now have directly write access to `gh-pages`. Just go ahead. We can revert commits if we don't like it. :sun_with_face:

**Comment by koppor** [comment]
If you want to discuss something, I propose to use [GrabNDrop](http://www.scyv.de/gnd/) to quickly create a screenshot and attach it to the PR (via drag'n'drop of the small window of GrabNDrop).

**Comment by mlep** [comment]
Well, is there a way to have a "real" preview (i.e. including the background colors)?
At the moment, the only way I have found it commit, pull & merge...

**Comment by koppor** [comment]
I tried to document at [README.md](https://github.com/JabRef/www.jabref.org) how to setup Jekyll locally. It works on Windows without issues. Does it at your side?

**Comment by koppor** [comment]
There is an issue when parsing `bg: #2A7722`. The `#` causes issues.

**Comment by koppor** [comment]
Solution: quote the whole color. You can use double quotes (`"`) or single quotes ( `'`). I fixed it locally, but @mlep also has pushed a fix, therefore, I'll recheck tomorrow to avoid conflicts at @mlep. :smiley:

**Pull request closed without merging**
