### PR TITLE
Complete redesign

### PR DESCRIPTION
**Pull request by tobiasdiez**
This is a complete redesign. 
image
@JabRef/developers @JabRef/translators Feedback welcome!

Things to do:
- [x] Replace screenshots: ideas?

### CODE REVIEW

**Comment by stefan-kolb** [comment]
<3

**Comment by mlep** [comment]
Nice!

For not disappointing new users, it should be made more obvious that the main target of JabRef is (La)TeX (it is, right?).

**Comment by tobiasdiez** [comment]
That's a good point @mlep. I wasn't sure how much emphasize to put on BibTeX. On the one hand, it's what JabRef is currently known for - on the other hand, we do support LibreOffice, Word and I'm currently using a bib file in connection with pandoc which works great for markdown-based files. Why do you think new users would be disappointed if we don't emphasize BibTex?

**Comment by mlep** [comment]
Although not using it, I think that, at the moment, you cannot directly insert citations in ms word from JabRef (as stated in https://discourse.jabref.org/t/directly-insert-citations-in-microsoft-word-by-jabref/1297 , https://discourse.jabref.org/t/tools-to-make-ms-word-libreoffice-workflow-easier/1827/2 , and https://discourse.jabref.org/t/how-can-i-insert-a-citation-into-word-docx/386 ).
So, I guess that, at the moment, using JabRef for ms word is not as direct as a regular ms word user may be used to.

**Comment by mlep** [comment]
Another thing about not disappointing users: for many people, "works across all of your devices" may include Android. (but, well, we can wait for users asking for it :wink: ).

**Comment by Siedlerchr** [comment]
Agree, we should emphasize a bit on bibtex/latex and also mabye cross plattform (mac, win, linux)? instead of all devices

**Comment by tobiasdiez** [comment]
Thanks for the feedback. Updated version is now ready for review:
image

**Comment by tobiasdiez** [comment]
Following the positive feedback, let's be brave and merge this now ;-)

**Pull request merged**
